### ISSUE TITLE
check virtual machine on new project base

### ISSUE THREAD

**Issue by miwo100** [miwo100/tikki#1]
tikki ist set up completely new as pure nodejs express application. Meteor is out.

Please do the following tasks to be sure everything is still running fine:

- Check the virtual machine is still running fine. Please note to remove Meteor from the provisioner . Meteor is not used anymore.
- last pls get tikki running on the virtual machine as described here: https://github.com/miwo100/tikki (under contribute a little bit further down)

**Comment by sbmueller** [comment]
Should I push changes to the provisioning script to leave out meteor && run the new commands to set up the project?

**Comment by miwo100** [comment]
Yes  , definitely

Von meinem iPhone gesendet

**Comment by sbmueller** [comment]
Virtual machine runs fine. However, setting up tikki fails now. Executing `npm run start` in the graphqlServer directory leads to:
```
> tikkiserver@0.0.0 start /home/vagrant/tikki/graphqlServer
> node ./index

WARNING: No configurations found in configuration directory:/home/vagrant/tikki/graphqlServer/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/home/vagrant/tikki/graphqlServer/node_modules/config/lib/config.js:180
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "GITHUB_ACCESS_TOKEN" is not defined
    at Config.get (/home/vagrant/tikki/graphqlServer/node_modules/config/lib/config.js:180:11)
    at Object.<anonymous> (/home/vagrant/tikki/graphqlServer/api/connectors/github/githubConnector.js:3:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/tikki/graphqlServer/index.js:11:25)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! tikkiserver@0.0.0 start: `node ./index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tikkiserver@0.0.0 start script 'node ./index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tikkiserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tikkiserver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tikkiserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/tikki/graphqlServer/npm-debug.log

```
I think there might be missing some steps in the readme?

**Comment by miwo100** [comment]
@sbmueller bitte noch unter /config eine local.json basierend auf local.json.template anlegen und <replace with github access token> ersetzen. Folgt separat.
